//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1DV402.S2.L3C {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_1DV402.S2.L3C.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        internal static string area {
            get {
                return ResourceManager.GetString("area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cirkel.
        /// </summary>
        internal static string circle {
            get {
                return ResourceManager.GetString("circle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ange figurens diameter: .
        /// </summary>
        internal static string circleInputText {
            get {
                return ResourceManager.GetString("circleInputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tryck tangent för att fortsätta.
        /// </summary>
        internal static string continuePromt {
            get {
                return ResourceManager.GetString("continuePromt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rätblock.
        /// </summary>
        internal static string cuboid {
            get {
                return ResourceManager.GetString("cuboid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ange figurens längd, bredd och höjd: .
        /// </summary>
        internal static string cuboidInputText {
            get {
                return ResourceManager.GetString("cuboidInputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cylinder.
        /// </summary>
        internal static string cylinder {
            get {
                return ResourceManager.GetString("cylinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ange figurens radier och höjd:.
        /// </summary>
        internal static string cylinderInputText {
            get {
                return ResourceManager.GetString("cylinderInputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detaljer.
        /// </summary>
        internal static string details {
            get {
                return ResourceManager.GetString("details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =====================================.
        /// </summary>
        internal static string divider {
            get {
                return ResourceManager.GetString("divider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ellips.
        /// </summary>
        internal static string ellipse {
            get {
                return ResourceManager.GetString("ellipse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ange figurens radier: .
        /// </summary>
        internal static string ellipseInputText {
            get {
                return ResourceManager.GetString("ellipseInputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEL! Ange ett nummer mellan 0 och 8..
        /// </summary>
        internal static string ErrorMessage1 {
            get {
                return ResourceManager.GetString("ErrorMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEL! Ett fel inträfade då figurens dimensioner tolkades..
        /// </summary>
        internal static string ErrorMessage2 {
            get {
                return ResourceManager.GetString("ErrorMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avsluta.
        /// </summary>
        internal static string finish {
            get {
                return ResourceManager.GetString("finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geometriska figurer.
        /// </summary>
        internal static string geometricObjects {
            get {
                return ResourceManager.GetString("geometricObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Höjd.
        /// </summary>
        internal static string height {
            get {
                return ResourceManager.GetString("height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Längd.
        /// </summary>
        internal static string length {
            get {
                return ResourceManager.GetString("length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MantelArea.
        /// </summary>
        internal static string mantelArea {
            get {
                return ResourceManager.GetString("mantelArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ange menuval [0-8]: .
        /// </summary>
        internal static string menuChoice {
            get {
                return ResourceManager.GetString("menuChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omkrets.
        /// </summary>
        internal static string perimeter {
            get {
                return ResourceManager.GetString("perimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slumpa 2D-figurer.
        /// </summary>
        internal static string random2D {
            get {
                return ResourceManager.GetString("random2D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slumpa 3D-figurer.
        /// </summary>
        internal static string random3D {
            get {
                return ResourceManager.GetString("random3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rektangel.
        /// </summary>
        internal static string rectangle {
            get {
                return ResourceManager.GetString("rectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ange figurens längd och bredd: .
        /// </summary>
        internal static string rectangleInputText {
            get {
                return ResourceManager.GetString("rectangleInputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sfär.
        /// </summary>
        internal static string sphere {
            get {
                return ResourceManager.GetString("sphere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ange figurens radie: .
        /// </summary>
        internal static string sphereInputText {
            get {
                return ResourceManager.GetString("sphereInputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begränsningsarea.
        /// </summary>
        internal static string totalSurfaceArea {
            get {
                return ResourceManager.GetString("totalSurfaceArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volym.
        /// </summary>
        internal static string volume {
            get {
                return ResourceManager.GetString("volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bredd.
        /// </summary>
        internal static string width {
            get {
                return ResourceManager.GetString("width", resourceCulture);
            }
        }
    }
}
